"""LayoutLMv3 document-understanding: real Hugging Face Transformers
inference on the actual uploaded document, reusing the SAME PaddleOCR output
the Phase 4 pipeline already produces — no separate/fake OCR run for this.

MODEL: microsoft/layoutlmv3-base — publicly available, PRETRAINED checkpoint.
Microsoft did not fine-tune this checkpoint for any specific downstream task;
we do not either. It is used purely as a frozen feature extractor.

TASK: document-type classification. A small linear classification head
(768 -> num_classes) is trained on top of LayoutLMv3's frozen pooled [CLS]
embedding. The head is trained by `scripts/train_layoutlm_classifier.py` on a
SYNTHETIC demo dataset generated by this project's own document renderer —
see that script and `layoutlm_head/training_metadata.json` for exact
dataset size, label set, split and measured validation accuracy. This is a
small demo-scale classifier, not a production-accuracy model, and is never
described as one.

MODEL STATUS: pretrained backbone (unmodified) + demo-scale trained head.

Fallback contract: any failure here (model not downloaded, OOM, corrupt
image, no OCR words) is caught and reported as `status="error"` /
`fallback_used=True` — callers must fall back to the existing OCR-keyword
classifier from Phase 4, and the result must never be presented as if it
came from the model.
"""

from __future__ import annotations

import json
import logging
import os
import threading
import time
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from app.config import get_settings
from app.services import ocr_service

logger = logging.getLogger("app.layoutlm")
settings = get_settings()

MODEL_CHECKPOINT = "microsoft/layoutlmv3-base"

# Engineering thresholds, not statistically validated — the classifier head
# is trained on a small synthetic dataset (see module docstring), so these
# are conservative, documented cutoffs rather than calibrated probabilities.
CONFIDENCE_HIGH = 0.75
CONFIDENCE_MEDIUM = 0.50

_processor = None
_model = None
_load_error: str | None = None
_lock = threading.Lock()

_head_weight: np.ndarray | None = None  # (num_classes, 768)
_head_bias: np.ndarray | None = None  # (num_classes,)
_head_labels: list[str] | None = None
_head_error: str | None = None


def _head_dir() -> str:
    return os.path.join(settings.model_cache_dir, "layoutlm_head")


def _load_backbone() -> None:
    global _processor, _model, _load_error

    if not settings.layoutlm_enabled:
        _load_error = "LayoutLMv3 disabled via LAYOUTLM_ENABLED=false"
        logger.info(_load_error)
        return

    os.makedirs(settings.model_cache_dir, exist_ok=True)
    # HF_HOME is set as a side effect of `app.config` being imported (see
    # that module) — early enough to apply even to huggingface_hub imports
    # triggered transitively by PaddleX during OCR engine load.

    checkpoint = settings.layoutlm_model_name
    try:
        import torch  # noqa: F401
        from transformers import LayoutLMv3Model, LayoutLMv3Processor

        logger.info("Loading LayoutLMv3 backbone (%s)...", checkpoint)
        _processor = LayoutLMv3Processor.from_pretrained(checkpoint, apply_ocr=False)
        _model = LayoutLMv3Model.from_pretrained(checkpoint)
        _model.eval()
        logger.info("LayoutLMv3 backbone loaded.")
    except Exception as exc:  # noqa: BLE001 - convert any load failure into a reported, non-fatal blocker
        _load_error = f"{type(exc).__name__}: {exc}"
        logger.error("LayoutLMv3 backbone failed to load: %s", _load_error)


def _load_head() -> None:
    global _head_weight, _head_bias, _head_labels, _head_error
    d = _head_dir()
    weights_path = os.path.join(d, "head.json")
    if not os.path.exists(weights_path):
        _head_error = (
            f"No trained classifier head found at {weights_path}. Run "
            "backend/scripts/train_layoutlm_classifier.py first."
        )
        return
    try:
        with open(weights_path, "r", encoding="utf-8") as f:
            payload = json.load(f)
        _head_weight = np.array(payload["weight"], dtype=np.float32)
        _head_bias = np.array(payload["bias"], dtype=np.float32)
        _head_labels = payload["labels"]
    except Exception as exc:  # noqa: BLE001
        _head_error = f"Failed to load classifier head: {type(exc).__name__}: {exc}"


def _ensure_loaded() -> None:
    global _model
    if _model is None and _load_error is None:
        with _lock:
            if _model is None and _load_error is None:
                _load_backbone()
    if _head_labels is None and _head_error is None:
        with _lock:
            if _head_labels is None and _head_error is None:
                _load_head()


def ocr_to_words_and_boxes(ocr_result: ocr_service.OCRResult, image_shape: tuple[int, int]) -> tuple[list[str], list[list[int]]]:
    """Converts the Phase 4 PaddleOCR output into LayoutLMv3's expected
    word-level tokens + 0-1000 normalized boxes.

    PaddleOCR (in the configuration this project uses) returns LINE-level
    boxes, not word-level ones. Each word in a line is assigned that line's
    full bounding box as an approximation — documented here, not hidden —
    since true per-word boxes aren't available from the upstream OCR step.
    """
    height, width = image_shape[:2]
    words: list[str] = []
    boxes: list[list[int]] = []
    for line in ocr_result.lines:
        if not line.box or not line.text.strip():
            continue
        xs = [pt[0] for pt in line.box]
        ys = [pt[1] for pt in line.box]
        x0, y0, x1, y1 = min(xs), min(ys), max(xs), max(ys)
        norm_box = [
            max(0, min(1000, int(1000 * x0 / width))),
            max(0, min(1000, int(1000 * y0 / height))),
            max(0, min(1000, int(1000 * x1 / width))),
            max(0, min(1000, int(1000 * y1 / height))),
        ]
        for word in line.text.split():
            words.append(word)
            boxes.append(norm_box)
    return words, boxes


@dataclass
class LayoutLMResult:
    status: str  # "success" | "error" | "unavailable"
    document_type: str | None = None
    confidence: float = 0.0
    processing_time_ms: int = 0
    fallback_used: bool = True
    error: str | None = None
    model: str = field(default_factory=lambda: settings.layoutlm_model_name)

    def to_dict(self) -> dict[str, Any]:
        return {
            "model": self.model,
            "status": self.status,
            "document_type": self.document_type,
            "confidence": round(self.confidence, 4),
            "processing_time_ms": self.processing_time_ms,
            "fallback_used": self.fallback_used,
        }


def embed(image: np.ndarray, words: list[str], boxes: list[list[int]]):
    """Runs the real LayoutLMv3 forward pass and returns the pooled [CLS]
    embedding as a numpy array. Raises on any failure — callers handle it."""
    import torch
    from PIL import Image as PILImage

    rgb = image[:, :, ::-1] if image.shape[-1] == 3 else image  # BGR (OpenCV) -> RGB (PIL)
    pil_image = PILImage.fromarray(rgb)

    encoding = _processor(pil_image, words, boxes=boxes, return_tensors="pt", truncation=True)
    with torch.no_grad():
        outputs = _model(**encoding)
    cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze(0).numpy()
    return cls_embedding


def _softmax(x: np.ndarray) -> np.ndarray:
    e = np.exp(x - np.max(x))
    return e / e.sum()


def classify_document_type(image: np.ndarray, ocr_result: ocr_service.OCRResult) -> LayoutLMResult:
    t0 = time.time()
    _ensure_loaded()

    if _model is None:
        return LayoutLMResult(status="unavailable", fallback_used=True, error=_load_error or "model not loaded")
    if _head_labels is None:
        return LayoutLMResult(status="unavailable", fallback_used=True, error=_head_error or "classifier head not loaded")

    words, boxes = ocr_to_words_and_boxes(ocr_result, image.shape)
    if not words:
        return LayoutLMResult(status="error", fallback_used=True, error="No OCR words available to feed LayoutLMv3")

    try:
        cls_embedding = embed(image, words, boxes)
        logits = _head_weight @ cls_embedding + _head_bias
        probs = _softmax(logits)
        best_idx = int(np.argmax(probs))
        elapsed_ms = int((time.time() - t0) * 1000)
        return LayoutLMResult(
            status="success",
            document_type=_head_labels[best_idx],
            confidence=float(probs[best_idx]),
            processing_time_ms=elapsed_ms,
            fallback_used=False,
        )
    except Exception as exc:  # noqa: BLE001 - inference failure must degrade, not crash the upload
        logger.error("LayoutLMv3 inference failed: %s", exc)
        return LayoutLMResult(status="error", fallback_used=True, error=f"{type(exc).__name__}: {exc}")


def confidence_band(confidence: float) -> str:
    if confidence >= CONFIDENCE_HIGH:
        return "HIGH"
    if confidence >= CONFIDENCE_MEDIUM:
        return "MEDIUM"
    return "LOW"


def status() -> dict[str, Any]:
    return {
        "backbone_loaded": _model is not None,
        "backbone_error": _load_error,
        "head_loaded": _head_labels is not None,
        "head_error": _head_error,
        "labels": _head_labels,
    }
